/**
 * Centralized sheet-to-Supabase mapping.
 *
 * NOTE (migration 0053, 2026-09-02): every table/view/function/trigger/RLS-
 * policy in this project's public schema was renamed with an `sss_` prefix
 * (e.g. `tickets` -> `sss_tickets`), so this schema can later be migrated
 * into an existing production Supabase project's DB without name collisions.
 * Explicit user decision — every object got the prefix, no exceptions. The
 * `supabaseTable` values below already reflect the new (prefixed) names;
 * historical/narrative text elsewhere in this file that mentions the old
 * unprefixed names (in prose, describing past migrations) was left as-is —
 * only the actual identifiers matter going forward.
 *
 * The legacy backend is a single wide "Ticket_Enquiry" Google Sheet — every
 * pipeline stage (Ticket-and-Enquiry, Quotation, Follow-Up, Site Visit,
 * Invoice, ...) reads/writes its own slice of columns on the same row.
 *
 * The Supabase side is normalized instead: one table per stage, each FKing
 * on the root `sss_tickets` table (owned by src/pages/Ticket-and-Enquiry.jsx)
 * via `ticket_uuid -> sss_tickets.uuid` (the real primary key — migration 0030;
 * before that, the FK was on tickets.ticket_id, the "TN-XXXX" business key).
 * `ticket_id` text is still kept on every stage table as a plain
 * denormalized column — populated at insert time, used throughout the app
 * for display/search/joins — it's just no longer the enforced relational
 * key. As each page is migrated off the sheet, add its table + field
 * mapping here rather than inventing a new scheme per page — this file is
 * the one place that should ever need to change field names, and it lets a
 * future migration script or codemod walk every stage's mapping
 * generically instead of hardcoding each one.
 */

/**
 * @typedef {Object} FieldMapping
 * @property {string} sheetColumn - Column letter in the Ticket_Enquiry sheet (e.g. "A").
 * @property {number} sheetIndex - 0-indexed position in the `row` array returned by
 *   the Apps Script `?sheet=Ticket_Enquiry` endpoint (row[sheetIndex]).
 * @property {string} sheetField - The camelCase field name currently used for this
 *   value across the React codebase's fetchData() mappings.
 * @property {string} supabaseColumn - The snake_case column name in the Supabase table.
 * @property {string} type - Postgres column type.
 * @property {string} [note] - Anything non-obvious about this field.
 */

/** @type {Record<string, { supabaseTable: string, sourceSheet: string, primaryKey: string, description: string, fields: FieldMapping[] }>} */
export const SCHEMA_MAPPING = {
  ticketEnquiry: {
    supabaseTable: "sss_tickets",
    sourceSheet: "Ticket_Enquiry",
    primaryKey: "uuid",
    description:
      "Root ticket record, owned by src/pages/Ticket-and-Enquiry.jsx. Created via the 'insertTicket' action; edited in place via 'update'. " +
      "Primary key is `uuid` (gen_random_uuid()); `ticket_id` is a separate unique, business-facing id (generated by the tickets_set_ticket_id() " +
      "trigger) that stage tables still FK against — nothing changes there since FKs only require uniqueness, not PK-ness.",
    fields: [
      { sheetColumn: "A", sheetIndex: 0, sheetField: "timeStemp", supabaseColumn: "created_at", type: "timestamptz" },
      { sheetColumn: "B", sheetIndex: 1, sheetField: "ticketId", supabaseColumn: "ticket_id", type: "text", note: "Generated by the tickets_set_ticket_id() trigger on insert; unique (not the primary key — see `uuid` above)." },
      { sheetColumn: "C", sheetIndex: 2, sheetField: "sourceOfEnquiry", supabaseColumn: "source_of_enquiry", type: "text" },
      { sheetColumn: "D", sheetIndex: 3, sheetField: "callType", supabaseColumn: "call_type", type: "text" },
      { sheetColumn: "E", sheetIndex: 4, sheetField: "enquiryReceiverName", supabaseColumn: "enquiry_receiver_name", type: "text" },
      { sheetColumn: "F", sheetIndex: 5, sheetField: "clientType", supabaseColumn: "client_type", type: "text" },
      { sheetColumn: "G", sheetIndex: 6, sheetField: "companyName", supabaseColumn: "company_name", type: "text" },
      { sheetColumn: "H", sheetIndex: 7, sheetField: "clientName", supabaseColumn: "client_name", type: "text" },
      { sheetColumn: "I", sheetIndex: 8, sheetField: "phoneNumber", supabaseColumn: "phone_number", type: "text" },
      { sheetColumn: "K", sheetIndex: 10, sheetField: "siteAddress", supabaseColumn: "site_address", type: "text" },
      { sheetColumn: "L", sheetIndex: 11, sheetField: "gstNo", supabaseColumn: "gst_no", type: "text" },
      { sheetColumn: null, sheetIndex: null, sheetField: "gstAddress", supabaseColumn: "gst_address", type: "text", note: "NEW column, migration 0050 — reintroduces the field dropped in migration 0029 (see notFields below for that history), now actually populated: required via UI validation (not DB-enforced) and, for Existing clients, autofilled together with gstNo from the production Lead-To-Order-Supabase-New project's lto_client_master.billing_address (not the retired company_details table). Shown as 'Billing Address' on Invoice.jsx's Pending tab." },
      { sheetColumn: "M", sheetIndex: 12, sheetField: "machineName", supabaseColumn: "machine_name", type: "text", note: "Comma-joined list of selected machines." },
      { sheetColumn: "N", sheetIndex: 13, sheetField: "category", supabaseColumn: "category", type: "text", note: "Labeled 'Category' in the UI (single-select). History: sheet col N -> 'category' -> renamed to 'enquiry_type' in migration 0015 -> renamed BACK to 'category' in migration 0043 (freed up by column T's field moving to 'sub_category' first), when a genuinely new 'enquiry_type' field was introduced. Sourced from dropdown category='category' (NABL/Service/Spare-style values)." },
      { sheetColumn: "O", sheetIndex: 14, sheetField: "mentionIssue", supabaseColumn: "mention_issue", type: "text" },
      { sheetColumn: "P", sheetIndex: 15, sheetField: "serviceLocation", supabaseColumn: "service_location", type: "text" },
      { sheetColumn: "Q", sheetIndex: 16, sheetField: "challanCopy", supabaseColumn: "challan_copy", type: "text", note: "Drive file URL; only set when serviceLocation === 'Warehouse'." },
      { sheetColumn: "R", sheetIndex: 17, sheetField: "machinePhoto", supabaseColumn: "machine_photo", type: "text", note: "Drive file URL; only set when serviceLocation === 'Warehouse'." },
      { sheetColumn: "S", sheetIndex: 18, sheetField: "videoCall", supabaseColumn: "video_call", type: "text", note: "'Yes' or 'No'." },
      { sheetColumn: "T", sheetIndex: 19, sheetField: "subCategory", supabaseColumn: "sub_category", type: "text", note: "Labeled 'Sub-Category' in the UI (multi-select, comma-joined). History: sheet col T -> 'new_category' -> renamed to 'category' in migration 0015 -> renamed to 'sub_category' in migration 0043 (to free up the 'category' name for column N above). Sourced from dropdown category='sub_category' (machine-group values)." },
      { sheetColumn: null, sheetIndex: null, sheetField: "enquiryType", supabaseColumn: "enquiry_type", type: "text", note: "NEW column, migration 0043 — not from the legacy sheet. Labeled 'Enquiry Type' in the UI (single-select), sourced from dropdown category='enquiry_type' (brand new, initially empty — seed via Master > Dropdown). Intended to drive planned/TAT calculation for stages AFTER Invoice (not yet implemented as of this migration)." },
      { sheetColumn: "U", sheetIndex: 20, sheetField: "videoCallTime", supabaseColumn: "video_call_time", type: "text" },
      { sheetColumn: "V", sheetIndex: 21, sheetField: "engineerAssign", supabaseColumn: "engineer_assign", type: "text" },
      { sheetColumn: "AJ", sheetIndex: 35, sheetField: "otp", supabaseColumn: "otp", type: "text", note: "Only generated when videoCall === 'Yes'." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "site_visit_otp", type: "text", note: "Added in migration 0032. Live/regeneratable OTP for src/pages/SiteVisitOTPVerification.jsx (stage 8) — mirrors the `otp` column's pattern for Video-Call, but kept separate since the two stages' OTP lifecycles are independent. Set/replaced by that page's 'Resend OTP'; snapshotted into otp_verification.otp_entered once verified." },
      { sheetColumn: "DX", sheetIndex: 127, sheetField: "CREName", supabaseColumn: "cre_name", type: "text" },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "warranty_check_planned", type: "timestamptz", note: "Gates Warranty-Check (src/pages/Warranty-Check.jsx): pending once set and no matching warranty_check row exists yet. Establishes the naming convention for future stages — a stage-specific `<next_stage>_planned` column on the owning table, rather than one shared generic `planned_at`. Originally stamped as a plain new Date() at ticket creation; changed in a later pass (no migration number — Ticket-and-Enquiry.jsx code change only) to be TAT-based via stagePlanning.js's 'warrantyCheck' rule: this ticket's own submit-time timestamp + tat_config['Warranty-Check'].duration_minutes, for consistency with every other stage's planned-column calculation." },
    ],
    notFields: [
      "This page also reads (but never writes) three cross-stage flags purely to hide tickets that " +
      "moved past this stage: row[34] col AI (video-call-done yes/no, owned by VideoCallSolution), " +
      "row[37] col AL (Quotation's planned timestamp), row[112] col DI (an invoice-done marker). " +
      "Those belong on their owning stage's future table, not on `tickets` — once those stages are " +
      "migrated, this page's Supabase query should filter via a join instead of local sheet columns.",
      "gst_address (sheet col J, 'Billing Address' in the UI) was dropped in migration 0029 — it was always " +
      "blank in practice. For Existing clients the field autofilled from company_details.billing_address, " +
      "which itself is always null (0 of 1594 seeded companies have a real value); New-client submissions " +
      "weren't populating it either (0 of 2 live rows had a non-empty value). Removed from the table and " +
      "every migrated page's fetch/display/form (Ticket-and-Enquiry, Warranty-Check, Video-Call, Quotation, " +
      "FollowUp, SiteVisitPlan). REINTRODUCED in migration 0050 (2026-09-01) as a genuinely-populated field — " +
      "see the gst_address field entry above — once its data source moved from the always-null " +
      "company_details table to the production Lead-To-Order-Supabase-New project's lto_client_master.",
    ],
  },

  loginMaster: {
    supabaseTable: "sss_login_users",
    sourceSheet: "Login Master",
    primaryKey: "uuid",
    description:
      "App accounts, wired into src/store/authStore.js's login() (called from src/pages/Login.jsx). " +
      "Auth goes through the public.login(p_username, p_password) Postgres RPC — RLS blocks anon from " +
      "reading/writing this table directly, since the anon key is public in the browser bundle and this " +
      "table holds plaintext passwords (stored unhashed by explicit request, matching the sheet). " +
      "src/pages/Settings.jsx (admin-only, role-gated, see App.jsx's ProtectedRoute requiredRole prop) " +
      "manages rows through four more RPCs in the same security-definer pattern: admin_list_users() " +
      "(no password column), admin_create_user(...), admin_update_user(...) (password arg optional — " +
      "omit/blank to leave unchanged), admin_delete_user(p_uuid). None of these RPCs can verify the " +
      "caller is actually an admin at the DB level — there's no Supabase Auth session here — so, same as " +
      "the rest of this app's backend, they're trusted-endpoint security, not real authorization.",
    fields: [
      { sheetColumn: "A", sheetIndex: 0, sheetField: "name", supabaseColumn: "full_name", type: "text", note: "Human display name. The app's runtime `user.username` (and localStorage 'currentUsername', used for CREName/engineerAssign matching everywhere) is populated from THIS field, not the login table's `username` column — see below." },
      { sheetColumn: "B", sheetIndex: 1, sheetField: "id", supabaseColumn: "username", type: "text", note: "Short login handle typed into the username field, e.g. 'engineer', 'admin'. Only consumed by the login RPC — never exposed to the rest of the app as `user.username`." },
      { sheetColumn: "C", sheetIndex: 2, sheetField: "password", supabaseColumn: "password", type: "text", note: "Stored in plain text, not hashed." },
      { sheetColumn: "D", sheetIndex: 3, sheetField: "role", supabaseColumn: "role", type: "public.user_role (enum: 'admin' | 'user' | 'engineer')" },
      { sheetColumn: "E", sheetIndex: 4, sheetField: "page", supabaseColumn: "page", type: "text[]", note: "Array of allowed page names (elements may have leading/trailing whitespace, trimmed client-side), matched against Sidebar.jsx's `navigation` array." },
    ],
    notFields: [
      "The sheet's 'Manual' and 'Deployemnt Link' columns (F, G) aren't used by the app's login flow and were left out.",
      "The legacy sheet let a user log in with EITHER column A or column B as the username (case-insensitive, " +
      "see Code.gs handleLogin). This table only supports column B's value as the login credential — logging " +
      "in with the column A / full_name value no longer works.",
    ],
  },

  dropdown: {
    supabaseTable: "sss_dropdown",
    sourceSheet: "DROPDOWN",
    primaryKey: "uuid",
    description:
      "Flat option-list table (one row per option, grouped by `category`) used by every migrated stage's " +
      "dropdowns — Ticket-and-Enquiry, Video-Call ('Service Type', 'Alternate Engineer', 'Item Name'), " +
      "Quotation ('Engineer Assign', 'Quotation Share By') and FollowUp ('Engineer Assign'). Each page's " +
      "fetchMasterSheet()/DROPDOWN_CATEGORY_TO_KEY picks only the categories it actually uses and maps them " +
      "to the display key its own JSX expects. Categories are seeded incrementally as each consuming page " +
      "needs one, not all at once — a category not seeded yet just renders an empty select/datalist, not an " +
      "error. IMPORTANT: always fetch through src/lib/supabase/dropdown.js's fetchDropdownRows() — never a " +
      "plain .select() — it paginates past Supabase's default 1000-row response cap, which item_name alone " +
      "exceeds (~1400 rows). A plain unpaginated fetch silently truncates and was a real live bug in " +
      "Ticket-and-Enquiry.jsx and VideoCallSolution.jsx (fixed once discovered) before this helper existed.",
    fields: [
      { sheetColumn: null, sheetField: null, supabaseColumn: "category", type: "text", note: "One of: call_type, source_of_enquiry, enquiry_receiver_name, category, sub_category, enquiry_type, service_location, engineer_assign_name, machine_name, item_name, quotation_share_by, transportation, payment_term, payment_mode, invoice_posted_by, acceptance_via." },
      { sheetColumn: null, sheetField: null, supabaseColumn: "value", type: "text" },
    ],
    notFields: [
      "category='category' corresponds to sheet header 'Requirement Service Category' (masterData[0][\"Category\"] in Ticket-and-Enquiry.jsx), labeled 'Category' in the UI (single-select) — renamed from dropdown category='enquiry_type' in migration 0043 (values unchanged: NABL/Service/Spare-style combos) when tickets.enquiry_type was renamed to tickets.category. Not to be confused with...",
      "category='sub_category' corresponds to sheet header 'Category' (masterData[0][\"Sub-Category\"] in Ticket-and-Enquiry.jsx), labeled 'Sub-Category' in the UI (multi-select) — renamed from dropdown category='category' in migration 0043 (values unchanged: machine-group names) when tickets.category was renamed to tickets.sub_category. A completely different option list from 'category' above, despite the similar naming.",
      "category='enquiry_type' is a BRAND NEW category introduced in migration 0043 (initially empty, no rows seeded yet) — sources Ticket-and-Enquiry.jsx's brand new 'Enquiry Type' field (tickets.enquiry_type, also new), intended to drive planned/TAT calculation for stages after Invoice. Seed via Master > Dropdown once the actual option list is decided.",
      "category='item_name' corresponds to sheet header 'Item-Name' (masterData[0][\"Item-Name\"] in VideoCallSolution.jsx) — seeded in migration 0025, 1414 unique values (case-insensitive de-dup) extracted live from the DROPDOWN sheet, a real spare-parts catalog rather than a short fixed list.",
      "category='quotation_share_by' corresponds to sheet header 'Quotation shared by' (masterData[0][\"Quotation Share by\"] in Quotation.jsx) — seeded in migration 0026, 14 unique values.",
      "category='payment_term' corresponds to the Master sheet's 'Payment Terms' column (masterData[0][\"Payment Terms\"] in OrderReceived.jsx) — seeded in migration 0034, 8 unique values (e.g. 'Against Delivery', '1'..'45' day terms, 'FOC').",
      "category='payment_mode' corresponds to the Master sheet's 'Payment Mode' column (masterData[0][\"Payment Mode\"] in OrderReceived.jsx) — seeded in migration 0034, 8 unique values (includes 'FOC', which closes the ticket at Order Received instead of proceeding to Invoice — see order_received.invoice_planned).",
      "category='invoice_posted_by' corresponds to the Master sheet's 'Invoice Posted By(Drop-Down)' column (masterData[0][\"Invoice Posted By(Drop-Down)\"] in Invoice.jsx) — seeded in migration 0037, 6 unique values.",
      "category='acceptance_via' (masterData[0][\"Acceptance Via\"] in OrderReceived.jsx) — new in migration 0049, 3 values (PO, Mail, Whatsapp). Replaced a hardcoded single-option ('Mail' only) select.",
      "The DROPDOWN sheet has many more columns (e.g. Expense Approval lists, etc.) used by pages not migrated yet — those aren't in this table.",
    ],
  },

  companyDetails: {
    supabaseTable: "sss_company_details",
    sourceSheet: "DROPDOWN",
    primaryKey: "uuid",
    description:
      "RETIRED as of 2026-09-01 — this table still exists (and its data is untouched) but nothing in the app " +
      "reads or writes it anymore. It used to back Ticket-and-Enquiry.jsx's 'Company Name' autofill and " +
      "Master/Dropdown.jsx's 'Company Details' tab (a full CRUD admin screen); both were switched to fetch " +
      "LIVE from the production Lead-To-Order-Supabase-New project's `lto_client_master` table instead, via " +
      "the new `ltoSupabase` client (src/lib/supabase/ltoClient.js) — see [[servicesupport_migration_project]] " +
      "memory. Reason: company_details.billing_address was always null in practice (see the fields note " +
      "below), while lto_client_master is the real, actively-maintained source of company master data. " +
      "Master/Dropdown.jsx's Company Details tab is now read-only (no Add/Edit/Delete) since editing belongs " +
      "in the production project, not this testing one. Safe to drop this table entirely once confirmed " +
      "nothing else references it.",
    fields: [
      { sheetColumn: null, sheetField: null, supabaseColumn: "company_name", type: "text", note: "Sheet header 'Company-Name'." },
      { sheetColumn: null, sheetField: null, supabaseColumn: "billing_address", type: "text", note: "Sheet header is actually 'GST Address', not 'Billing Address' as the app code assumes (masterData[0][\"Billing Address\"] is always empty — a pre-existing bug, left as-is). Of 1594 companies, 0 had a real value here; the one non-blank cell found was placeholder text ('add data in DROPDOWN sheet'), normalized to null." },
      { sheetColumn: null, sheetField: null, supabaseColumn: "gst_number", type: "text", note: "Sheet header 'GST-No.'." },
    ],
  },

  tatConfig: {
    supabaseTable: "sss_tat_config",
    sourceSheet: null,
    primaryKey: "uuid",
    description:
      "TAT (turnaround time) config, one row per stage, managed via src/pages/Master/tat-config.jsx (admin " +
      "only). src/lib/supabase/stagePlanning.js's getStageTatMinutes() reads duration_minutes by stage_name " +
      "(falls back to 60 if that stage isn't seeded yet) for every `<next_stage>_planned` calculation across " +
      "the app. stage_name is now restricted client-side to a fixed list (tat-config.jsx's ALL_STAGE_NAMES, " +
      "migration 2026-08-26) matching stagePlanning.js's actual tatStageName values — the 'New Stage' form " +
      "used to accept free-text names, which could silently drift out of sync with what stagePlanning.js " +
      "looks up. responsible_person (migration 0047) is a free-text admin-entered name shown as the " +
      "'Responsible' column on Dashboard.jsx's Generate Report PDF, replacing an earlier hardcoded map.",
    fields: [
      { sheetColumn: null, sheetField: null, supabaseColumn: "stage_name", type: "text", note: "Unique. One of ALL_STAGE_NAMES in tat-config.jsx — must match a stagePlanning.js rule's tatStageName exactly." },
      { sheetColumn: null, sheetField: null, supabaseColumn: "duration_minutes", type: "integer", note: "TAT for this stage, in minutes. Entered via a Days/Hours/Minutes split in the UI, stored as one total." },
      { sheetColumn: null, sheetField: null, supabaseColumn: "responsible_person", type: "text", note: "Migration 0047. Free-text — who owns this stage's TAT. Shown on Dashboard.jsx's PDF report; null falls back to that page's own hardcoded STAGE_RESPONSIBLE map." },
      { sheetColumn: null, sheetField: null, supabaseColumn: "updated_at", type: "timestamptz" },
    ],
  },

  officeHours: {
    supabaseTable: "sss_office_hours",
    sourceSheet: null,
    primaryKey: "id",
    description:
      "SINGLETON config row (id is fixed at 1 via a check constraint — there is only ever one row), migration " +
      "0047. Managed via src/pages/Master/tat-config.jsx's 'Office Hours' tab. " +
      "src/lib/supabase/stagePlanning.js's computeStagePlanned() reads this (+ the holidays table) on every " +
      "call and confines the computed `<next_stage>_planned` timestamp to this working window via " +
      "addBusinessMinutes() — a stage submitted after closing time, or whose TAT would run past it, rolls the " +
      "leftover TAT minutes over to the next working day's opening time instead of landing outside office " +
      "hours. Seeded with a default (10:00-18:00, Sunday off) so this always has a row even before an admin " +
      "configures it.",
    fields: [
      { sheetColumn: null, sheetField: null, supabaseColumn: "id", type: "integer", note: "Always 1 — enforced by a check constraint, not just convention." },
      { sheetColumn: null, sheetField: null, supabaseColumn: "start_time", type: "time" },
      { sheetColumn: null, sheetField: null, supabaseColumn: "end_time", type: "time" },
      { sheetColumn: null, sheetField: null, supabaseColumn: "weekly_off_days", type: "integer[]", note: "JS Date.getDay() values (0=Sunday..6=Saturday) that recur as off EVERY week — e.g. {0} = every Sunday. One-off exception dates go in the separate `holidays` table instead, per explicit user decision (not re-added here every week)." },
      { sheetColumn: null, sheetField: null, supabaseColumn: "updated_at", type: "timestamptz" },
    ],
  },

  holidays: {
    supabaseTable: "sss_holidays",
    sourceSheet: null,
    primaryKey: "id",
    description:
      "One-off non-working dates (national/company holidays), migration 0047, ON TOP OF office_hours." +
      "weekly_off_days' recurring weekly off-days. Managed via src/pages/Master/tat-config.jsx's 'Holidays' " +
      "tab. src/lib/supabase/stagePlanning.js's computeStagePlanned()/addBusinessMinutes() skip these dates " +
      "the same way they skip weekly_off_days when computing `<next_stage>_planned`.",
    fields: [
      { sheetColumn: null, sheetField: null, supabaseColumn: "holiday_date", type: "date", note: "Unique — one entry per date." },
      { sheetColumn: null, sheetField: null, supabaseColumn: "holiday_name", type: "text" },
      { sheetColumn: null, sheetField: null, supabaseColumn: "created_at", type: "timestamptz" },
    ],
  },

  warrantyCheck: {
    supabaseTable: "sss_warranty_check",
    sourceSheet: "Ticket_Enquiry",
    primaryKey: "id",
    description:
      "Stage 2, owned by src/pages/Warranty-Check.jsx. Gated by tickets.warranty_check_planned (stamped on " +
      "ticket creation): a ticket is 'pending' once that's set and no row exists here for it yet; it " +
      "becomes 'history' the moment a row is inserted. Unlike `tickets`, there's no placeholder row created " +
      "early and updated later — a single insert happens at submission time, carrying created_at (this " +
      "stage's own 'actual') and the result fields together. delay_minutes is computed by a BEFORE " +
      "INSERT/UPDATE trigger (public.warranty_check_set_delay(), migration 0017) as " +
      "round((tickets.warranty_check_planned - warranty_check.created_at) in minutes) — negative when this " +
      "stage finished late, positive when early; never set from the frontend. The legacy sheet-column " +
      "mapping this replaced (row[22]:row[27] / W:AB) had overlapping/broken indices (e.g. row[23] was read " +
      "as both 'category' and 'actual3') — a pre-existing bug from this page never having been finished, " +
      "not something intentionally preserved here.",
    fields: [
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "ticket_uuid", type: "uuid", note: "FK -> tickets(uuid), the real relational key (migration 0030). Unique — one row per ticket." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "ticket_id", type: "text", note: "Plain denormalized column (no longer the FK, see ticket_uuid) — still populated at insert, used for display/search." },
      { sheetColumn: "Z", sheetIndex: 25, sheetField: "warrantyCheck", supabaseColumn: "warranty_check", type: "text", note: "'yes' or 'no'." },
      { sheetColumn: "AA", sheetIndex: 26, sheetField: "billNumber", supabaseColumn: "bill_number", type: "text", note: "Only set when warranty_check = 'yes'." },
      { sheetColumn: "AB", sheetIndex: 27, sheetField: "billAttachment", supabaseColumn: "bill_attachment", type: "text", note: "File URL in the 'ticket_enquiry' Supabase Storage bucket (path prefix 'warranty/'), replacing the old Google Drive upload. Only set when warranty_check = 'yes'." },
      { sheetColumn: "X", sheetIndex: 23, sheetField: "actual3", supabaseColumn: "created_at", type: "timestamptz", note: "Defaults to now() at insert time; doubles as this stage's completion timestamp." },
      { sheetColumn: "AO", sheetIndex: 37, sheetField: null, supabaseColumn: "video_call_planned", type: "timestamp without time zone", note: "Renamed from 'planned_at' in migration 0019 to match the <next_stage>_planned convention. Computed by src/lib/supabase/stagePlanning.js's 'videoCall' rule and submitted by the frontend at insert time: NULL unless tickets.service_location != 'Warehouse' AND tickets.video_call = 'Yes' (see warehouse_planned/quotation_planned below — the three are mutually exclusive, checked in that priority order in Warranty-Check.jsx's handleSubmit); otherwise warranty_check's own submit-time timestamp + tat_config['Video-Call'].duration_minutes. Gates src/pages/VideoCallSolution.jsx." },
      { sheetColumn: "Y", sheetIndex: 24, sheetField: null, supabaseColumn: "delay_minutes", type: "integer", note: "Trigger-computed only, see description above. Never written by the frontend." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "warehouse_planned", type: "timestamptz", note: "Added in migration 0035, reworked in 0038 and 0040. TWO writers: (1) stagePlanning.js's 'warehouse' rule, submitted by the frontend on THIS row at Warranty-Check submit time, ONLY when tickets.service_location = 'Warehouse' (takes priority over video_call_planned/quotation_planned that same submit); (2) public.video_call_apply_downstream_planned() (AFTER INSERT on video_call, migration 0040) once a video_call attempt resolves with enquiry_solved='no' AND that attempt's service_type = 'Warehouse' — NOT mutually exclusive with quotation_planned in that case (see below); both get stamped, so the ticket is pending in both Warehouse.jsx and Quotation.jsx simultaneously until each is completed independently (explicit, user-confirmed choice)." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "quotation_planned", type: "timestamptz", note: "Added in migration 0021, reworked in 0035, 0038 and 0040. Readiness stamp for Quotation, centralized here regardless of which path a ticket took. THREE writers: (1) stagePlanning.js's 'quotationDirect' rule, submitted by the frontend at insert time on THIS row when the ticket matches neither warehouse_planned's nor video_call_planned's condition (service_location != 'Warehouse' AND video_call != 'Yes') — the ticket skips both Warehouse and Video-Call entirely; (2) public.warehouse_apply_quotation_planned() (AFTER INSERT on warehouse) once the Warehouse path completes; (3) public.video_call_apply_downstream_planned() (AFTER INSERT on video_call, renamed from video_call_apply_quotation_planned in migration 0040) whenever a video_call attempt resolves with enquiry_solved='no' on the Video-Call path — regardless of service_type, so this always fires alongside warehouse_planned's writer (2) above when service_type='Warehouse'. Lives here rather than on video_call/warehouse/tickets specifically so Quotation.jsx only ever has to check one column regardless of which path a ticket took." },
    ],
  },

  videoCall: {
    supabaseTable: "sss_video_call",
    sourceSheet: "Ticket_Enquiry",
    primaryKey: "id",
    description:
      "Stage 3, owned by src/pages/VideoCallSolution.jsx. Gated by warranty_check.video_call_planned. Unlike " +
      "warranty_check, this table is NOT one-row-per-ticket — an enquiry_solved = 'rescheduled' outcome must " +
      "leave a history record without permanently closing out the ticket (another user may complete it " +
      "later), so multiple attempts per ticket_id are allowed. A ticket is 'pending' when it has no video_call " +
      "row yet, OR its LATEST row (by created_at) has enquiry_solved = 'rescheduled'; it's 'history' once the " +
      "latest row is 'yes' or 'no'. The live/regeneratable OTP during the pending phase (the Resend/Regenerate " +
      "button, which persists immediately) stays on tickets.otp — there's no video_call row to hold it until " +
      "an attempt is actually submitted. otp_generation here is only the final snapshot of whatever OTP was " +
      "verified at submit time (only set when enquiry_solved = 'yes'). delay_minutes is trigger-computed " +
      "(public.video_call_set_delay(), migration 0021) as warranty_check.video_call_planned - " +
      "video_call.created_at, in minutes — same negative-when-late/positive-when-early convention as " +
      "warranty_check.delay_minutes. An AFTER INSERT trigger (public.video_call_apply_downstream_planned(), " +
      "renamed from video_call_apply_quotation_planned in migration 0040) writes back to " +
      "warranty_check.quotation_planned whenever enquiry_solved='no', and ALSO to " +
      "warranty_check.warehouse_planned when that same 'no' attempt's service_type = 'Warehouse' (not " +
      "mutually exclusive — both get stamped in that case; see those fields' notes on the warrantyCheck entry).",
    fields: [
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "ticket_uuid", type: "uuid", note: "FK -> tickets(uuid), the real relational key (migration 0030). NOT unique — multiple attempts allowed (see description)." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "ticket_id", type: "text", note: "Plain denormalized column (no longer the FK, see ticket_uuid) — still populated at insert, used for display/search." },
      { sheetColumn: "AF", sheetIndex: 31, sheetField: "videoCallServicesSolve", supabaseColumn: "enquiry_solved", type: "text", note: "'yes' | 'no' | 'rescheduled'." },
      { sheetColumn: "AG", sheetIndex: 32, sheetField: "afterVideoCallGenerateOTP", supabaseColumn: "otp_generation", type: "text", note: "Snapshot of tickets.otp at the moment it was verified — only set when enquiry_solved = 'yes'. The live/regeneratable value stays on tickets.otp while pending." },
      { sheetColumn: "AH", sheetIndex: 33, sheetField: "otpVarificationStatus", supabaseColumn: "regeneration_status", type: "text", note: "Final outcome status: 'Verified' | 'Rescheduled' | 'Skipped'. The legacy sheet also used this column's value 'Regenerated OTP' as a live interim marker during Resend/Regenerate — that interim state isn't persisted here since it happens before any video_call row exists." },
      { sheetColumn: "AI", sheetIndex: 34, sheetField: "audioUrl", supabaseColumn: "audio_link", type: "text", note: "Supabase Storage URL, replacing the old Google Drive upload. Only set when enquiry_solved = 'no'." },
      { sheetColumn: "AJ", sheetIndex: 35, sheetField: "remarks", supabaseColumn: "remarks", type: "text" },
      { sheetColumn: "AK", sheetIndex: 36, sheetField: "itemQty", supabaseColumn: "item_qty", type: "jsonb", note: "[{ item, qty }, ...]. Only set when enquiry_solved = 'no'. Stored as jsonb instead of the legacy stringified-JSON text." },
      { sheetColumn: "AL", sheetIndex: 37, sheetField: "serviceType", supabaseColumn: "service_type", type: "text", note: "Only set when enquiry_solved = 'no'." },
      { sheetColumn: "AM", sheetIndex: 38, sheetField: "rescheduledTime", supabaseColumn: "rescheduled_time", type: "timestamptz", note: "Only set when enquiry_solved = 'rescheduled'." },
      { sheetColumn: "AN", sheetIndex: 39, sheetField: "alternateEngineer", supabaseColumn: "alternate_engineer", type: "text", note: "Only set when enquiry_solved = 'rescheduled'." },
      { sheetColumn: "AD", sheetIndex: 29, sheetField: "actual2", supabaseColumn: "created_at", type: "timestamptz", note: "Defaults to now() at insert time; doubles as this attempt's completion timestamp." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "delay_minutes", type: "integer", note: "Trigger-computed only, see description above. Never written by the frontend." },
    ],
    notFields: [
      "The page's 'Cancel Ticket' flow (handleSubmitCancel) now inserts into public.cancelled_tickets " +
      "(migration 0046) instead of the legacy 'Cancel' sheet — see that table's own entry below. It's a " +
      "separate destination table, not part of this stage's own table.",
    ],
  },

  quotation: {
    supabaseTable: "sss_quotation",
    sourceSheet: "Ticket_Enquiry",
    primaryKey: "id",
    description:
      "Stage 4, owned by src/pages/Quotation.jsx. Gated by warranty_check.quotation_planned. A ticket can be " +
      "quoted, then revised any number of times — the frontend upserts by ticket_id (migration 0023 added " +
      "the UPDATE policy this needs) rather than inserting once, so quotation_no/basic_amount/etc. just get " +
      "overwritten in place on the same row. created_at is NOT touched by revisions (only set via the column " +
      "default on the original insert), so it still means 'first quoted at' for delay_minutes purposes. " +
      "follow_up_planned is only included in the upsert payload on the FIRST save for a ticket (Quotation.jsx " +
      "checks a client-side hasQuotation flag) — omitted on every later revision so it's never overwritten; " +
      "revising a quotation must not restart FollowUp's readiness clock. Quotation.jsx's own Pending/History " +
      "tabs are NOT a partition: Pending = every gated ticket whose LATEST follow_up row (if any) isn't " +
      "stage='Order Received' (checked client-side in Quotation.jsx's fetchData, not a DB-level gate — a " +
      "ticket can be revised right up until Order Received closes it out); History = the subset that's been " +
      "quoted at least once, purely for browsing past quotations, UNAFFECTED by Order Received — a ticket " +
      "can be, and usually is, in both simultaneously, and also simultaneously pending in FollowUp.jsx once " +
      "quoted. " +
      "delay_minutes is trigger-computed (public.quotation_set_delay(), migration 0022) as " +
      "warranty_check.quotation_planned - quotation.created_at, in minutes — same " +
      "negative-when-late/positive-when-early convention as the prior stages.",
    fields: [
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "ticket_uuid", type: "uuid", note: "FK -> tickets(uuid), the real relational key (migration 0030). Unique — the upsert's onConflict target (was ticket_id before 0030)." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "ticket_id", type: "text", note: "Plain denormalized column (no longer the FK, see ticket_uuid) — still populated at insert, used for display/search." },
      { sheetColumn: "AR", sheetIndex: 43, sheetField: "quotationNo", supabaseColumn: "quotation_no", type: "text" },
      { sheetColumn: "AS", sheetIndex: 44, sheetField: "basicAmount", supabaseColumn: "basic_amount", type: "numeric" },
      { sheetColumn: "AT", sheetIndex: 45, sheetField: "totalQutation", supabaseColumn: "total_amount", type: "numeric", note: "Labeled 'Total Amount with Tax' in the form." },
      { sheetColumn: "AU", sheetIndex: 46, sheetField: "quotationPdfLink", supabaseColumn: "quotation_pdf_link", type: "text", note: "File URL in the 'ticket_enquiry' Supabase Storage bucket (path prefix 'quotation/'), replacing the old Google Drive upload." },
      { sheetColumn: "AV", sheetIndex: 47, sheetField: "quotationShareBy", supabaseColumn: "quotation_share_by", type: "text", note: "Dropdown not seeded in the `dropdown` table (not used by the Ticket-and-Enquiry form) — renders empty until seeded." },
      { sheetColumn: "AW", sheetIndex: 48, sheetField: "shareThrough", supabaseColumn: "share_through", type: "text", note: "Always 'Mail' — hardcoded by the frontend regardless of the form's 'Quotation Share' Yes/No answer, which was never actually persisted even in the legacy sheet. Pre-existing gap, preserved as-is." },
      { sheetColumn: "AX", sheetIndex: 49, sheetField: "remarks", supabaseColumn: "remarks", type: "text" },
      { sheetColumn: "AP", sheetIndex: 41, sheetField: "actual3", supabaseColumn: "created_at", type: "timestamptz", note: "Defaults to now() at insert time; doubles as this stage's completion timestamp." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "follow_up_planned", type: "timestamptz", note: "Readiness stamp for Follow-Up (next stage). Submitted by the frontend; rule TBD — see description above." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "delay_minutes", type: "integer", note: "Trigger-computed only, see description above. Never written by the frontend." },
    ],
    notFields: [
      "The page's 'Cancel Ticket' flow now inserts into public.cancelled_tickets (migration 0046) — same as " +
      "video_call's Cancel flow.",
      "The pending/history 'Item List' button shows the latest video_call row's item_qty (only populated when " +
      "that stage's enquiry_solved = 'no') — this table has no item list field of its own; a ticket only " +
      "reaches Quotation via that path or by skipping Video-Call entirely (in which case the item list is empty).",
    ],
  },

  followUp: {
    supabaseTable: "sss_follow_up",
    sourceSheet: "Follow-Up",
    primaryKey: "id",
    description:
      "Stage 5, owned by src/pages/FollowUp.jsx. Gated by quotation.follow_up_planned. Append-only log — " +
      "EVERY submission (either stage) is its own permanent row, never updated, matching the legacy Follow-Up " +
      "sheet's own always-insert behavior. Two stages: 'Followup' (a call log; never closes anything, ticket " +
      "stays in FollowUp's pending list no matter how many of these pile up) and 'Order Received' (closes it " +
      "out — a ticket leaves FollowUp's pending list once ANY row for it has this stage, regardless of order). " +
      "order_received_planned is a placeholder readiness stamp for the next stage (OrderReceived.jsx, not yet " +
      "migrated — still reads directly from the live sheet's CN column, which the OLD FollowUp.jsx used to " +
      "stamp via an Apps Script call; that stamp no longer happens now that FollowUp.jsx is fully cut over, so " +
      "OrderReceived.jsx will stop receiving new tickets until it's migrated to read order_received_planned " +
      "from here instead — migrating it should follow shortly after this). site_visit_planned (migration 0027) " +
      "is submitted ONLY when stage = 'Order Received' AND the ticket's effective service type = 'Site Visit' " +
      "— that's video_call.service_type from its latest attempt WHEN one exists, but falls back to " +
      "tickets.service_location when the ticket has no video_call row at all (tickets.video_call = 'No', so " +
      "it skipped that stage entirely and service_type was never set anywhere). FollowUp.jsx computes this " +
      "fallback client-side before checking against 'Site Visit'. " +
      "delay_minutes (also 0027, added after the table's initial creation in 0023) is trigger-computed " +
      "(public.follow_up_set_delay()) as quotation.follow_up_planned - follow_up.created_at, per row.",
    fields: [
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "ticket_uuid", type: "uuid", note: "FK -> tickets(uuid), the real relational key (migration 0030). NOT unique — every submission is its own log row." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "ticket_id", type: "text", note: "Plain denormalized column (no longer the FK, see ticket_uuid) — still populated at insert, used for display/search." },
      { sheetColumn: "C", sheetIndex: 2, sheetField: "stage", supabaseColumn: "stage", type: "text", note: "'Followup' | 'Order Received'. Hardcoded 2-option select in the UI, not a `dropdown` table category — these exact values drive different form branches in code." },
      { sheetColumn: "D", sheetIndex: 3, sheetField: "engineerAssign", supabaseColumn: "engineer_assign", type: "text" },
      { sheetColumn: "E", sheetIndex: 4, sheetField: "whatDidCustomerSay", supabaseColumn: "what_did_customer_say", type: "text", note: "Only set when stage = 'Followup'." },
      { sheetColumn: "F", sheetIndex: 5, sheetField: "nextAction", supabaseColumn: "next_action", type: "text", note: "Only set when stage = 'Followup'." },
      { sheetColumn: "G", sheetIndex: 6, sheetField: "nextDateOfCall", supabaseColumn: "next_date_of_call", type: "date", note: "Only set when stage = 'Followup'." },
      { sheetColumn: "H", sheetIndex: 7, sheetField: "clientAttachmentUrl", supabaseColumn: "client_attachment_url", type: "text", note: "Supabase Storage URL (path prefix 'follow_up/'), replacing the old Google Drive upload. Only set when stage = 'Order Received'." },
      { sheetColumn: "A", sheetIndex: 0, sheetField: "timestamp", supabaseColumn: "created_at", type: "timestamptz", note: "Defaults to now() at insert time; this log row's own timestamp." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "order_received_planned", type: "timestamptz", note: "Submitted by the frontend when stage = 'Order Received' as new Date() (no calculation rule — this stage's own gate, not TAT-derived). Gates src/pages/OrderReceived.jsx (migrated in 0033)." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "site_visit_planned", type: "timestamptz", note: "Submitted by the frontend when stage = 'Order Received' AND video_call.service_type = 'Site Visit'. See description above." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "delay_minutes", type: "integer", note: "Trigger-computed only, see description above. Never written by the frontend." },
    ],
    notFields: [
      "The page's 'Cancel Ticket' flow now inserts into public.cancelled_tickets (migration 0046) — same as " +
      "Video-Call's and Quotation's Cancel flows.",
    ],
  },

  siteVisit: {
    supabaseTable: "sss_site_visit",
    sourceSheet: "Ticket_Enquiry",
    primaryKey: "id",
    description:
      "Stage 6, owned by src/pages/SiteVisitPlan.jsx. Gated by follow_up.site_visit_planned (latest non-null " +
      "value per ticket). One row per ticket, inserted once at submission — no revision support described for " +
      "this stage (unlike quotation). tada_planned is a placeholder readiness stamp for the next stage — not " +
      "yet identified or migrated — same 'add the column now, wire the consumer later' pattern used " +
      "throughout. delay_minutes is trigger-computed (public.site_visit_set_delay(), migration 0027) as " +
      "follow_up.site_visit_planned - site_visit.created_at, in minutes — same convention as prior stages. " +
      "'Warranty Check' shown in this page's UI is joined live from warranty_check.warranty_check for display " +
      "only, not stored on this table.",
    fields: [
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "ticket_uuid", type: "uuid", note: "FK -> tickets(uuid), the real relational key (migration 0030). Unique — one row per ticket." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "ticket_id", type: "text", note: "Plain denormalized column (no longer the FK, see ticket_uuid) — still populated at insert, used for display/search." },
      { sheetColumn: "EI", sheetIndex: 138, sheetField: "engineerAssign", supabaseColumn: "engineer_assign", type: "text" },
      { sheetColumn: "BM", sheetIndex: 64, sheetField: "dateOfVisit", supabaseColumn: "date_of_visit", type: "date" },
      { sheetColumn: "EY", sheetIndex: 154, sheetField: "travelTime", supabaseColumn: "travel_time", type: "time" },
      { sheetColumn: "BN", sheetIndex: 65, sheetField: "transportation", supabaseColumn: "transportation", type: "text", note: "Dropdown category 'transportation', seeded in migration 0028 from the DROPDOWN sheet's 'Transport Mode' column (8 values)." },
      { sheetColumn: "BK", sheetIndex: 62, sheetField: "actual5", supabaseColumn: "created_at", type: "timestamptz", note: "Defaults to now() at insert time; doubles as this stage's completion timestamp." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "tada_planned", type: "timestamptz", note: "Readiness stamp for TADA (src/pages/TADA.jsx, migrated in 0031). Submitted by the frontend at insert time as new.now()." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "delay_minutes", type: "integer", note: "Trigger-computed only, see description above. Never written by the frontend." },
    ],
    notFields: [
      "The legacy page also read payment_term/acceptance_via/payment_mode/senior_approval (sheet columns " +
      "BB:BG) for read-only display — these were never editable in the form and never actually written by any " +
      "known upstream page in the current pipeline (a pre-existing dead/unclear data source, not something " +
      "this migration created). They were dropped from this table; the corresponding pending/history table " +
      "columns in SiteVisitPlan.jsx now always render blank — a pre-existing gap made visible, not a new bug.",
      "The 'Visit Calendar' / 'Today's Availability' engineer-scheduling views also used to overlay Video-Call " +
      "and 'Repair Status' stage scheduling data from the sheet — neither exists in Supabase yet (Repair " +
      "Status hasn't been migrated at all), so those views now only reflect Site Visit history until those " +
      "stages are migrated too.",
      "The page's 'Cancel Ticket' flow now inserts into public.cancelled_tickets (migration 0046) — same as " +
      "Video-Call's, Quotation's, and Follow-Up's Cancel flows.",
    ],
  },

  tada: {
    supabaseTable: "sss_tada",
    sourceSheet: "Ticket_Enquiry",
    primaryKey: "id",
    description:
      "Stage 7, owned by src/pages/TADA.jsx. Gated by site_visit.tada_planned. One row per ticket, inserted " +
      "once at submission (no revision support, same as warranty_check/site_visit). otp_verification_planned " +
      "is submitted by the frontend at insert time, computed via src/lib/supabase/stagePlanning.js's " +
      "'otpVerification' rule as this row's own created_at + tat_config['OTP Verification'].duration_minutes " +
      "— gates the (not yet migrated) OTP Verification stage that follows TADA. delay_minutes is " +
      "trigger-computed (public.tada_set_delay(), migration 0031) as greatest(0, tada.created_at - " +
      "site_visit.tada_planned) in minutes — UNLIKE every prior stage's negative-when-late/positive-when-early " +
      "convention, this is always >= 0 (minutes late; 0 when on time or early), per explicit requirement for " +
      "this stage.",
    fields: [
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "ticket_uuid", type: "uuid", note: "FK -> tickets(uuid), the real relational key. Unique — one row per ticket." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "ticket_id", type: "text", note: "Plain denormalized column (not the FK) — populated at insert, used for display/search." },
      { sheetColumn: "CE", sheetIndex: null, sheetField: "travelDate", supabaseColumn: "travel_date", type: "date" },
      { sheetColumn: "CF", sheetIndex: null, sheetField: "returnDate", supabaseColumn: "return_date", type: "date" },
      { sheetColumn: "CG", sheetIndex: null, sheetField: "destination", supabaseColumn: "destination", type: "text" },
      { sheetColumn: "CH", sheetIndex: null, sheetField: "purposeOfTravel", supabaseColumn: "purpose_of_travel", type: "text" },
      { sheetColumn: "CI", sheetIndex: null, sheetField: "amount", supabaseColumn: "amount", type: "numeric" },
      { sheetColumn: "ET", sheetIndex: null, sheetField: "expectedCompletionDate", supabaseColumn: "expected_completion_date", type: "date" },
      { sheetColumn: "EU", sheetIndex: null, sheetField: "expectedCompletionTime", supabaseColumn: "expected_completion_time", type: "time" },
      { sheetColumn: "CC", sheetIndex: null, sheetField: "actual6", supabaseColumn: "created_at", type: "timestamptz", note: "Defaults to now() at insert time; doubles as this stage's completion timestamp." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "otp_verification_planned", type: "timestamptz", note: "Readiness stamp for the next stage (OTP Verification, not yet migrated). Submitted by the frontend, see description above." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "delay_minutes", type: "integer", note: "Trigger-computed only, see description above. Never negative. Never written by the frontend." },
    ],
    notFields: [
      "The legacy page's 'Cancel Ticket' flow (handleSubmitCancel, writes to a separate 'Cancel' sheet) isn't " +
      "part of this table or migrated yet — same as every other stage's Cancel flow.",
    ],
  },

  otpVerification: {
    supabaseTable: "sss_otp_verification",
    sourceSheet: "Ticket_Enquiry",
    primaryKey: "id",
    description:
      "Stage 8, owned by src/pages/SiteVisitOTPVerification.jsx. Gated by tada.otp_verification_planned. One " +
      "row per ticket, inserted once at submission (no revision support, same as warranty_check/site_visit/" +
      "tada). No outgoing `<next_stage>_planned` column yet — the stage that follows isn't identified. " +
      "delay_minutes is trigger-computed (public.otp_verification_set_delay(), migration 0032) as " +
      "greatest(0, otp_verification.created_at - tada.otp_verification_planned) in minutes — same " +
      "non-negative convention as tada.delay_minutes (never negative; 0 when on time or early). The OTP " +
      "check itself uses tickets.site_visit_otp (a new live/regeneratable column, separate from tickets.otp " +
      "which belongs to Video-Call) — 'Resend OTP' updates it directly; otp_entered here is only the final " +
      "snapshot at verification time.",
    fields: [
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "ticket_uuid", type: "uuid", note: "FK -> tickets(uuid), the real relational key. Unique — one row per ticket." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "ticket_id", type: "text", note: "Plain denormalized column (not the FK) — populated at insert, used for display/search." },
      { sheetColumn: "CC", sheetIndex: 80, sheetField: "siteVisitDate", supabaseColumn: "site_visit_date", type: "date" },
      { sheetColumn: "CD", sheetIndex: 81, sheetField: "otpVerification", supabaseColumn: "otp_entered", type: "text", note: "Snapshot of tickets.site_visit_otp at verification time." },
      { sheetColumn: "CF", sheetIndex: 83, sheetField: "serviceReportFile", supabaseColumn: "service_report_file", type: "text", note: "File URL in the 'ticket_enquiry' Supabase Storage bucket (path prefix 'otp_verification/'), replacing the old Google Drive upload." },
      { sheetColumn: "CH", sheetIndex: 85, sheetField: "quatationReceive", supabaseColumn: "quotation_receive_file", type: "text", note: "Same Storage bucket/prefix as service_report_file. Optional." },
      { sheetColumn: "CI", sheetIndex: 86, sheetField: "video", supabaseColumn: "video_link", type: "text", note: "Same Storage bucket/prefix. Client-side 100MB size cap, same as before." },
      { sheetColumn: "CJ", sheetIndex: 87, sheetField: "locallyPurchasedSpares", supabaseColumn: "locally_purchased_spares", type: "text", note: "'Yes' or 'No' — hardcoded 2-option select, not sourced from the dropdown table." },
      { sheetColumn: "CG", sheetIndex: 84, sheetField: "remarks", supabaseColumn: "remarks", type: "text" },
      { sheetColumn: "CA", sheetIndex: 78, sheetField: "actual11", supabaseColumn: "created_at", type: "timestamptz", note: "Defaults to now() at insert time; doubles as this stage's completion timestamp." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "delay_minutes", type: "integer", note: "Trigger-computed only, see description above. Never negative. Never written by the frontend." },
    ],
    notFields: [
      "The legacy page's 'Cancel Ticket' flow (handleSubmitCancel, writes to a separate 'Cancel' sheet) isn't " +
      "part of this table or migrated — removed from the migrated page entirely (same decision made for TADA).",
    ],
  },

  orderReceived: {
    supabaseTable: "sss_order_received",
    sourceSheet: "Ticket_Enquiry",
    primaryKey: "id",
    description:
      "Stage 9, owned by src/pages/OrderReceived.jsx. Gated by follow_up.order_received_planned (latest " +
      "non-null value per ticket, since follow_up is an append-only log) — this is the ONLY gate. Warehouse " +
      "tickets (both the direct Warranty-Check path and the video_call service_type='Warehouse' path) also " +
      "flow through Quotation -> Follow-Up like every other ticket (confirmed by user 2026-08-26 — an earlier " +
      "migration 0041 wrongly assumed the direct Warehouse path skipped Quotation/Follow-Up and added a " +
      "separate warehouse.order_received_planned gate; reverted by migration 0042), so they reach Order " +
      "Received the same way once their Follow-Up log records stage='Order Received'. One row per ticket, " +
      "inserted once at submission (no revision support, same as warranty_check/site_visit/tada/" +
      "otp_verification). " +
      "invoice_planned is submitted by the frontend at insert time, computed via " +
      "src/lib/supabase/stagePlanning.js's 'invoice' rule as this row's own created_at + " +
      "tat_config['Invoice'].duration_minutes — gates the (not yet migrated) Invoice stage that follows Order " +
      "Received. delay_minutes is trigger-computed (public.order_received_set_delay(), migration 0033) as " +
      "round((follow_up.order_received_planned - order_received.created_at)) in minutes — back to the " +
      "ORIGINAL negative-when-late/positive-when-early convention (matching Quotation/FollowUp), NOT the " +
      "non-negative convention introduced for tada/otp_verification.",
    fields: [
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "ticket_uuid", type: "uuid", note: "FK -> tickets(uuid), the real relational key. Unique — one row per ticket." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "ticket_id", type: "text", note: "Plain denormalized column (not the FK) — populated at insert, used for display/search." },
      { sheetColumn: "CQ", sheetIndex: 94, sheetField: "paymentTerm", supabaseColumn: "payment_term", type: "text", note: "Dropdown category 'payment_term', seeded in migration 0034 (8 values, from the Master sheet's 'Payment Terms' column)." },
      { sheetColumn: "CR", sheetIndex: 95, sheetField: "acceptanceVia", supabaseColumn: "acceptance_via", type: "text", note: "Dropdown category 'acceptance_via' (PO / Mail / Whatsapp), seeded in migration 0049 — was a hardcoded single-option select ('Mail' only) before." },
      { sheetColumn: "CS", sheetIndex: 96, sheetField: "seniorApprovalUrl", supabaseColumn: "senior_approval", type: "text", note: "File URL in the 'ticket_enquiry' Supabase Storage bucket (path prefix 'order_received/'). Renamed from senior_attachments in migration 0049. Only shown/required in the UI once a Payment Mode is picked, and skipped for payment_mode='FOC'." },
      { sheetColumn: "CT", sheetIndex: 97, sheetField: "paymentMode", supabaseColumn: "payment_mode", type: "text", note: "Dropdown category 'payment_mode', seeded in migration 0034 (8 values, from the Master sheet's 'Payment Mode' column, includes 'FOC'). Selecting 'FOC' closes the ticket at this stage — invoice_planned is left null instead of computed, see below." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "advance_payment_attachment", type: "text", note: "New in migration 0049. File URL in the 'ticket_enquiry' Storage bucket (path prefix 'order_received/'), proving advance payment received. Same conditional-on-Payment-Mode / skipped-for-FOC UI behavior as senior_approval." },
      { sheetColumn: "CO", sheetIndex: 92, sheetField: "actual", supabaseColumn: "created_at", type: "timestamptz", note: "Defaults to now() at insert time; doubles as this stage's completion timestamp." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "invoice_planned", type: "timestamptz", note: "Readiness stamp for the next stage (Invoice, not yet migrated). Submitted by the frontend, see description above. Left null when payment_mode='FOC' (migration 0049) — the ticket closes at Order Received instead of proceeding to Invoice." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "delay_minutes", type: "integer", note: "Trigger-computed only, see description above. Can be negative (late) or positive (early). Never written by the frontend." },
    ],
    notFields: [
      "The legacy page's 'Cancel Ticket' flow (handleSubmitCancel, writes to a separate 'Cancel' sheet) isn't " +
      "part of this table or migrated — removed from the migrated page entirely (same decision made for TADA " +
      "and OTP Verification).",
    ],
  },

  warehouse: {
    supabaseTable: "sss_warehouse",
    sourceSheet: "Ticket_Enquiry",
    primaryKey: "id",
    description:
      "Warehouse-repair stage, owned by src/pages/Warehouse.jsx. Gated by warranty_check.warehouse_planned, " +
      "set via TWO independent paths (migration 0040): (1) the frontend, at Warranty-Check submit time, when " +
      "tickets.service_location = 'Warehouse' (takes priority over that same submit's video_call_planned/" +
      "quotation_planned); (2) public.video_call_apply_downstream_planned() (AFTER INSERT on video_call) when " +
      "a video_call attempt resolves with enquiry_solved='no' AND service_type = 'Warehouse' — this path is " +
      "NOT mutually exclusive with Quotation, so such a ticket is pending in both Warehouse.jsx and " +
      "Quotation.jsx at once. One row per ticket, inserted once at submission (no revision support, same as " +
      "warranty_check/site_visit/tada). " +
      "delay_minutes is trigger-computed (public.warehouse_set_delay(), migration 0035) as " +
      "round((warranty_check.warehouse_planned - warehouse.created_at)) in minutes — the ORIGINAL " +
      "negative-when-late/positive-when-early convention, matching predecessor Warranty-Check. An AFTER " +
      "INSERT trigger (public.warehouse_apply_quotation_planned()) writes warranty_check.quotation_planned " +
      "once this stage completes — the SAME centralized column the video_call='Yes' path's " +
      "video_call_apply_quotation_planned() writes to, so Quotation.jsx's gating query needs no changes " +
      "regardless of which branch a ticket took — Warehouse-direct tickets flow into Quotation/Follow-Up the " +
      "same as every other path (confirmed by user 2026-08-26; a short-lived migration 0041 that tried to give " +
      "this path a separate direct-to-Order-Received shortcut was reverted by migration 0042).",
    fields: [
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "ticket_uuid", type: "uuid", note: "FK -> tickets(uuid), the real relational key. Unique — one row per ticket." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "ticket_id", type: "text", note: "Plain denormalized column (not the FK) — populated at insert, used for display/search." },
      { sheetColumn: "BR", sheetIndex: 69, sheetField: "assignedEngineer", supabaseColumn: "assigned_engineer", type: "text" },
      { sheetColumn: "BS", sheetIndex: 70, sheetField: "priority", supabaseColumn: "priority", type: "text", note: "'High' | 'Medium' | 'Low' — hardcoded 3-option select in the UI, not sourced from the dropdown table." },
      { sheetColumn: "BT", sheetIndex: 71, sheetField: "dateOfRepair", supabaseColumn: "date_of_repair", type: "date" },
      { sheetColumn: "BU", sheetIndex: 72, sheetField: "remarks", supabaseColumn: "remarks", type: "text" },
      { sheetColumn: "BP", sheetIndex: 67, sheetField: "actual7", supabaseColumn: "created_at", type: "timestamptz", note: "Defaults to now() at insert time; doubles as this stage's completion timestamp." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "delay_minutes", type: "integer", note: "Trigger-computed only, see description above. Never written by the frontend." },
    ],
  },

  invoice: {
    supabaseTable: "sss_invoice",
    sourceSheet: "Ticket_Enquiry",
    primaryKey: "id",
    description:
      "Stage 10, owned by src/pages/Invoice.jsx. Gated by order_received.invoice_planned. One row per ticket, " +
      "inserted once at submission (no revision support, same as prior stages). Branches into TWO independent " +
      "(non-exclusive-in-code, but practically exclusive since enquiry_type is single-select) next-stage " +
      "readiness stamps, both computed at insert time via src/lib/supabase/stagePlanning.js, migration 0045: " +
      "calibration_planned (this row's own created_at + tat_config['Calibration'].duration_minutes) ONLY when " +
      "tickets.enquiry_type = 'NABL' — gates Calibration (src/pages/Calibration.jsx); spare_dispatch_planned " +
      "(created_at + tat_config['Spare Dispatch'].duration_minutes) ONLY when tickets.enquiry_type = 'SPARE' " +
      "— gates Spare Dispatch Details (src/pages/SpareDispatchDetails.jsx). Any other enquiry_type value (or " +
      "none set) skips both branches entirely. " +
      "delay_minutes is trigger-computed (public.invoice_set_delay(), migration 0036) as " +
      "round((order_received.invoice_planned - invoice.created_at)) in minutes — the ORIGINAL " +
      "negative-when-late/positive-when-early convention (matching predecessor Order Received). The legacy " +
      "page's own fetchData()/fetchInvoiceSheet() duplicate a broken, unrelated copy of Ticket-and-Enquiry's " +
      "whole row shape (dead code, pre-existing) — only the fields handleSubmit actually persists are " +
      "modeled here.",
    fields: [
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "ticket_uuid", type: "uuid", note: "FK -> tickets(uuid), the real relational key. Unique — a ticket can only pass through this stage once." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "ticket_id", type: "text", note: "Plain denormalized column (not the FK) — populated at insert, used for display/search." },
      { sheetColumn: null, sheetIndex: null, sheetField: "invoicePostedBy", supabaseColumn: "invoice_posted_by", type: "text", note: "Dropdown category 'invoice_posted_by', seeded in migration 0037 (6 values)." },
      { sheetColumn: null, sheetIndex: null, sheetField: "invoiceDate", supabaseColumn: "invoice_date", type: "date", note: "Left blank by default in the Create Invoice modal (2026-09-01) — was previously pre-filled to today's date, which let CREs submit without ever actually checking/changing it, risking a wrong date on the invoice. The input is still `required`." },
      { sheetColumn: null, sheetIndex: null, sheetField: "invoiceNoNABL", supabaseColumn: "invoice_no_nabl", type: "text" },
      { sheetColumn: null, sheetIndex: null, sheetField: "invoiceNoSERVICE", supabaseColumn: "invoice_no_service", type: "text" },
      { sheetColumn: null, sheetIndex: null, sheetField: "invoiceNoSPARE", supabaseColumn: "invoice_no_spare", type: "text" },
      { sheetColumn: null, sheetIndex: null, sheetField: "invoiceAmountNABLBasic", supabaseColumn: "invoice_amount_nabl_basic", type: "numeric" },
      { sheetColumn: null, sheetIndex: null, sheetField: "invoiceAmountNABLGst", supabaseColumn: "invoice_amount_nabl_gst", type: "numeric" },
      { sheetColumn: null, sheetIndex: null, sheetField: "serviceAmountBasic", supabaseColumn: "service_amount_basic", type: "numeric" },
      { sheetColumn: null, sheetIndex: null, sheetField: "serviceAmountGST", supabaseColumn: "service_amount_gst", type: "numeric" },
      { sheetColumn: null, sheetIndex: null, sheetField: "totalServiceAmtSpare", supabaseColumn: "spare_amount_basic", type: "numeric", note: "Labeled 'Invoice Amount SPARE (Basic)' in the legacy sheet payload, despite the misleading formData field name." },
      { sheetColumn: null, sheetIndex: null, sheetField: "totalAmtWithGST", supabaseColumn: "spare_amount_gst", type: "numeric", note: "Labeled 'Invoice Amount SPARE (gst)' in the legacy sheet payload, despite the misleading formData field name." },
      { sheetColumn: null, sheetIndex: null, sheetField: "attachmentService", supabaseColumn: "attachment_service", type: "text", note: "File URL in the 'ticket_enquiry' Supabase Storage bucket (path prefix 'invoice/'), replacing the old Google Drive upload." },
      { sheetColumn: null, sheetIndex: null, sheetField: "attachmentSpear", supabaseColumn: "attachment_spear", type: "text", note: "Same Storage bucket/prefix as attachment_service." },
      { sheetColumn: null, sheetIndex: null, sheetField: "attachmentNABL", supabaseColumn: "attachment_nabl", type: "text", note: "Same Storage bucket/prefix as attachment_service." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "otp", type: "text", note: "Legacy 6-digit code generated client-side on submission — purpose unclear (nothing downstream verifies it), preserved as-is." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "created_at", type: "timestamptz", note: "Defaults to now() at insert time; doubles as this stage's completion timestamp." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "calibration_planned", type: "timestamptz", note: "Readiness stamp for Calibration.jsx — only set when tickets.enquiry_type='NABL'. See description above." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "spare_dispatch_planned", type: "timestamptz", note: "Migration 0045. Readiness stamp for SpareDispatchDetails.jsx — only set when tickets.enquiry_type='SPARE'. See description above." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "delay_minutes", type: "integer", note: "Trigger-computed only, see description above. Never written by the frontend." },
    ],
    notFields: [
      "The legacy page's 'Cancel Ticket' flow (handleSubmitCancel, writes to a separate 'Cancel' sheet) isn't " +
      "part of this table or migrated — removed from the migrated page entirely (same decision made for " +
      "TADA, OTP Verification, and Order Received).",
      "quotationNo/clientName/phoneNumber/emailAddress/category/companyName/quotationPdfLink were part of the " +
      "legacy sheet's Invoice row but are pure denormalized copies of data already available via tickets/" +
      "quotation joins — dropped, matching the convention every other stage table already follows (display " +
      "fields come from joins, not duplicated columns).",
    ],
  },

  calibration: {
    supabaseTable: "sss_calibration",
    sourceSheet: null,
    primaryKey: "id",
    description:
      "Calibration stage, owned by src/pages/Calibration.jsx (migration 0045 — previously an unmigrated, " +
      "sheet-wired page). Gated by invoice.calibration_planned, which is only ever set for " +
      "tickets.enquiry_type='NABL'. One row per ticket, inserted once at submission. " +
      "calibration_certificate_planned is submitted by the frontend at insert time, computed via " +
      "src/lib/supabase/stagePlanning.js's 'calibrationCertificate' rule as this row's own created_at + " +
      "tat_config['Calibration Certificate'].duration_minutes — gates the next stage, " +
      "src/pages/CalibrationCertificate.jsx (every Calibration submission gets this, no branching). " +
      "delay_minutes is trigger-computed (public.calibration_set_delay()) as " +
      "round((invoice.calibration_planned - calibration.created_at)) in minutes — the ORIGINAL " +
      "negative-when-late/positive-when-early convention (matching predecessor Invoice).",
    fields: [
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "ticket_uuid", type: "uuid", note: "FK -> tickets(uuid), the real relational key. Unique — a ticket can only pass through this stage once." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "ticket_id", type: "text", note: "Plain denormalized column (not the FK) — populated at insert, used for display/search." },
      { sheetColumn: null, sheetIndex: null, sheetField: "calibrationDate", supabaseColumn: "calibration_date", type: "date" },
      { sheetColumn: null, sheetIndex: null, sheetField: "calibrationPeriodMonth", supabaseColumn: "calibration_period_month", type: "integer" },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "calibration_due_date", type: "date", note: "calibration_date + calibration_period_month, computed client-side (informational only — when this calibration itself expires, not a stage-gating column)." },
      { sheetColumn: null, sheetIndex: null, sheetField: "calibrationUploadFile", supabaseColumn: "calibration_upload_file", type: "text", note: "File URL in the 'ticket_enquiry' Supabase Storage bucket (path prefix 'calibration/')." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "created_at", type: "timestamptz", note: "Defaults to now() at insert time; doubles as this stage's completion timestamp." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "calibration_certificate_planned", type: "timestamptz", note: "Readiness stamp for the next stage (Calibration Certificate). Submitted by the frontend, see description above." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "delay_minutes", type: "integer", note: "Trigger-computed only, see description above. Never written by the frontend." },
    ],
    notFields: [
      "The legacy page's Accountability/Approval and hard-copy/soft-copy status fields (accountablityApproval, " +
      "hardCopyStatus, hardCopyAttachment, softCopyStatus, softCopyAttachment, senderName) were part of a " +
      "separate AccountablityApproval.jsx flow that was explicitly removed from this app (not migrated) — " +
      "not modeled here.",
    ],
  },

  calibrationCertificate: {
    supabaseTable: "sss_calibration_certificate",
    sourceSheet: null,
    primaryKey: "id",
    description:
      "Calibration Certificate stage, owned by src/pages/CalibrationCertificate.jsx (migration 0045 — " +
      "previously an unmigrated, sheet-wired page). Gated by calibration.calibration_certificate_planned. " +
      "One row per ticket, inserted once at submission. No `<next_stage>_planned` column — per explicit " +
      "instruction, nothing comes after this stage yet (the final stage in the NABL/Calibration branch). " +
      "delay_minutes is trigger-computed (public.calibration_certificate_set_delay()) as " +
      "round((calibration.calibration_certificate_planned - calibration_certificate.created_at)) in minutes " +
      "— the ORIGINAL negative-when-late/positive-when-early convention (matching predecessor Calibration).",
    fields: [
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "ticket_uuid", type: "uuid", note: "FK -> tickets(uuid), the real relational key. Unique — a ticket can only pass through this stage once." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "ticket_id", type: "text", note: "Plain denormalized column (not the FK) — populated at insert, used for display/search." },
      { sheetColumn: null, sheetIndex: null, sheetField: "certificateTypeName", supabaseColumn: "certificate_type_name", type: "text" },
      { sheetColumn: null, sheetIndex: null, sheetField: "numberOfCertificatesDocuments", supabaseColumn: "number_of_certificates_documents", type: "integer" },
      { sheetColumn: null, sheetIndex: null, sheetField: "fullDestinationAddress", supabaseColumn: "full_destination_address", type: "text" },
      { sheetColumn: null, sheetIndex: null, sheetField: "dateOfDispatch", supabaseColumn: "date_of_dispatch", type: "date" },
      { sheetColumn: null, sheetIndex: null, sheetField: "courierCompanyName", supabaseColumn: "courier_company_name", type: "text" },
      { sheetColumn: null, sheetIndex: null, sheetField: "courierTrackingNumber", supabaseColumn: "courier_tracking_number", type: "text" },
      { sheetColumn: null, sheetIndex: null, sheetField: "expectedDeliveryDate", supabaseColumn: "expected_delivery_date", type: "date" },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "attachment", type: "text", note: "File URL in the 'ticket_enquiry' Supabase Storage bucket (path prefix 'calibration_certificate/')." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "created_at", type: "timestamptz", note: "Defaults to now() at insert time; doubles as this stage's completion timestamp." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "delay_minutes", type: "integer", note: "Trigger-computed only, see description above. Never written by the frontend." },
    ],
  },

  spareDispatchDetails: {
    supabaseTable: "sss_spare_dispatch_details",
    sourceSheet: null,
    primaryKey: "id",
    description:
      "Spare Dispatch stage, owned by src/pages/SpareDispatchDetails.jsx (new page, migration 0045). Gated " +
      "by invoice.spare_dispatch_planned, which is only ever set for tickets.enquiry_type='SPARE'. One row " +
      "per ticket, inserted once at submission. No `<next_stage>_planned` column — nothing comes after this " +
      "stage yet. delay_minutes is trigger-computed (public.spare_dispatch_details_set_delay()) as " +
      "round((invoice.spare_dispatch_planned - spare_dispatch_details.created_at)) in minutes — the " +
      "ORIGINAL negative-when-late/positive-when-early convention (matching predecessor Invoice).",
    fields: [
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "ticket_uuid", type: "uuid", note: "FK -> tickets(uuid), the real relational key. Unique — a ticket can only pass through this stage once." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "ticket_id", type: "text", note: "Plain denormalized column (not the FK) — populated at insert, used for display/search." },
      { sheetColumn: null, sheetIndex: null, sheetField: "transporterName", supabaseColumn: "transporter_name", type: "text" },
      { sheetColumn: null, sheetIndex: null, sheetField: "docketBiltyNo", supabaseColumn: "docket_bilty_no", type: "text" },
      { sheetColumn: null, sheetIndex: null, sheetField: "dispatchDate", supabaseColumn: "dispatch_date", type: "date" },
      { sheetColumn: null, sheetIndex: null, sheetField: "courierTransportDetails", supabaseColumn: "courier_transport_details", type: "text" },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "bilty_copy_attachment", type: "text", note: "File URL in the 'ticket_enquiry' Supabase Storage bucket (path prefix 'spare_dispatch/')." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "created_at", type: "timestamptz", note: "Defaults to now() at insert time; doubles as this stage's completion timestamp." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "delay_minutes", type: "integer", note: "Trigger-computed only, see description above. Never written by the frontend." },
    ],
  },

  makeQuotation: {
    supabaseTable: "sss_make_quotation",
    sourceSheet: "Make Quotation",
    primaryKey: "id",
    description:
      "src/pages/Quotation/MakeQuotation.jsx — a standalone GST quotation builder, NOT part of the ticket " +
      "pipeline (no ticket_id at all; driven by picking a company/consignee, not a specific ticket). PDF " +
      "generation stays entirely client-side (pdf-generator.jsx); only the upload target moved, from Google " +
      "Drive to the 'ticket_enquiry' Storage bucket (path prefix 'make_quotation/'). A 'revision' creates a " +
      "NEW row with a suffixed quotation_no (e.g. OT-25-26-2401 -> OT-25-26-2401-01 -> ...-02), not an update " +
      "to the original — quotation-service.jsx's getNextQuotationNumber() now computes the next sequence by " +
      "querying existing quotation_no values for the current prefix+financial-year instead of asking Apps " +
      "Script, with the same no-atomicity-guarantee tradeoff the legacy version already had (a low-stakes " +
      "internal numbering scheme, not part of the ticket_id generation trigger's guarantees). " +
      "quotation-service.jsx's dead second copy of this page (its unused default export) and its Apps-Script-" +
      "only getCompanyPrefix() were both deleted (2026-09-02) — only getNextQuotationNumber remains there now. " +
      "The 'Generate Link' feature (handleGenerateLink) was also unlinked from Apps Script the same day: it " +
      "now uploads the PDF straight to the 'ticket_enquiry' Storage bucket (path prefix 'make_quotation/') and " +
      "hands back that link for manual sharing — no automated email. Real email sending still needs a " +
      "Supabase Edge Function + an email provider, a separate infrastructure decision from this data migration.",
    fields: [
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "quotation_no", type: "text", note: "Unique. Client-generated (see description) or a revision suffix of an existing one." },
      { sheetColumn: null, sheetIndex: null, sheetField: "date", supabaseColumn: "quotation_date", type: "text" },
      { sheetColumn: null, sheetIndex: null, sheetField: "preparedBy", supabaseColumn: "prepared_by", type: "text" },
      { sheetColumn: null, sheetIndex: null, sheetField: "consignorState/Name/Address/Mobile/Phone/GSTIN/StateCode", supabaseColumn: "consignor_*", type: "text", note: "7 columns, one per consignor field." },
      { sheetColumn: null, sheetIndex: null, sheetField: "consigneeName/Address/State/ContactName/ContactNo/GSTIN/StateCode + shipTo/msmeNumber", supabaseColumn: "consignee_* / ship_to / msme_number", type: "text", note: "9 columns, one per consignee field." },
      { sheetColumn: null, sheetIndex: null, sheetField: "validity/paymentTerms/delivery/freight/insurance/taxes", supabaseColumn: "validity/payment_terms/delivery/freight/insurance/taxes", type: "text", note: "6 term columns." },
      { sheetColumn: null, sheetIndex: null, sheetField: "notes", supabaseColumn: "notes", type: "text", note: "Pipe-joined array, matching the legacy sheet's own storage format." },
      { sheetColumn: null, sheetIndex: null, sheetField: "accountNo/bankName/bankAddress/ifscCode/email/website/pan", supabaseColumn: "account_no/bank_name/bank_address/ifsc_code/email/website/pan", type: "text", note: "7 bank-details columns." },
      { sheetColumn: null, sheetIndex: null, sheetField: "specialOffers", supabaseColumn: "special_offers", type: "text", note: "Pipe-joined array." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "special_discount", type: "numeric", note: "Header-level only. The legacy sheet also repeated this value once per item row (Quotation Items); that per-row duplication wasn't carried over here — dropped as a de-dup cleanup, not a functional change." },
      { sheetColumn: null, sheetIndex: null, sheetField: "pdfUrl", supabaseColumn: "pdf_url", type: "text" },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "grand_total", type: "numeric" },
    ],
  },

  pipelineOverview: {
    supabaseTable: "sss_pipeline_overview",
    sourceSheet: null,
    primaryKey: "ticket_uuid",
    description:
      "Migration 0039. A read-only Postgres VIEW (not a table) joining every migrated stage side by side, one " +
      "row per ticket_uuid — mirrors the old wide Google Sheet layout (each stage's columns grouped together) " +
      "for MIS-style flattened reporting. NOT used by any page's pending/history gating logic — every page " +
      "still queries its own stage table(s) directly, exactly as documented elsewhere in this file. " +
      "video_call and follow_up (both allow multiple rows per ticket) are joined via a LATERAL subquery " +
      "picking only the LATEST row per ticket (by created_at) — full multi-attempt history is only in those " +
      "underlying tables, not here. Columns are prefixed per stage to avoid collisions: wc_ (Warranty-Check), " +
      "vc_ (Video-Call), wh_ (Warehouse), qt_ (Quotation), fu_ (Follow-Up), sv_ (Site Visit), td_ (TADA), " +
      "otp_ (OTP Verification), or_ (Order Received), inv_ (Invoice); tickets' own columns are unprefixed " +
      "except where they'd collide with a stage's own field of the same name (ticket_video_call, " +
      "ticket_video_call_time, ticket_otp, ticket_site_visit_otp, ticket_engineer_assign). Granted SELECT to " +
      "anon and authenticated explicitly (views need their own grant even when every underlying table already " +
      "has RLS policies for anon).",
    fields: [],
  },

  quotationItems: {
    supabaseTable: "sss_quotation_items",
    sourceSheet: "Quotation Items",
    primaryKey: "id",
    description: "Line items for make_quotation — one row per item per quotation_no. See makeQuotation entry above.",
    fields: [
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "quotation_no", type: "text", note: "FK -> make_quotation(quotation_no)." },
      { sheetColumn: null, sheetIndex: null, sheetField: "code/name/description/units", supabaseColumn: "code/name/description/units", type: "text" },
      { sheetColumn: null, sheetIndex: null, sheetField: "gst/qty/rate/discount/flatDiscount/amount", supabaseColumn: "gst/qty/rate/discount/flat_discount/amount", type: "numeric" },
    ],
  },

  cancelledTickets: {
    supabaseTable: "sss_cancelled_tickets",
    sourceSheet: "Cancel",
    primaryKey: "id",
    description:
      "'Cancel Ticket' log, owned by src/pages/Cancle.jsx (route /cancel), migration 0046. Migrates the " +
      "legacy 'Cancel' sheet — the four stage pages that have a 'Cancel Ticket' checkbox+remarks sub-form " +
      "(FollowUp.jsx, Quotation.jsx, SiteVisitPlan.jsx, VideoCallSolution.jsx) now insert here instead of " +
      "POSTing to Apps Script. Append-only, no unique constraint on ticket_uuid (a ticket could in principle " +
      "be cancelled from more than one stage's form — same as the legacy sheet allowed). Client-facing " +
      "display fields (client_name/phone_number/company_name/category/mention_issue/cre_name) are NOT " +
      "duplicated here — Cancle.jsx joins back to `tickets` for those, fixing a pre-existing gap in the " +
      "legacy flow (its sheet row shape had no real ticket link, so role='user' CRE-name filtering on that " +
      "page silently never worked). " +
      "IMPORTANT, explicit user decision (2026-08-26): cancelling a ticket ONLY removes it from the " +
      "cancelling page's own pending list (client-side filter, unchanged from legacy behavior) — it does NOT " +
      "globally exclude the ticket from any other stage's pending query. Making 'cancelled' a real cross-stage " +
      "gate was explicitly deferred, not an oversight.",
    fields: [
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "ticket_uuid", type: "uuid", note: "FK -> tickets(uuid), the real relational key." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "ticket_id", type: "text", note: "Plain denormalized column (not the FK) — populated at insert, used for display/search." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "cancelled_from_stage", type: "text", note: "Which page's form submitted the cancellation: 'Follow-Up' | 'Quotation' | 'Site Visit Plan' | 'Video Call Solution'." },
      { sheetColumn: null, sheetIndex: null, sheetField: "cancelRemarks", supabaseColumn: "remarks", type: "text" },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "created_at", type: "timestamptz", note: "Defaults to now() at insert time." },
    ],
    notFields: [
      "The legacy sheet row also carried title/description fields — these were always-blank artifacts (the " +
      "ticket data model has no such fields) and were dropped, not modeled here.",
    ],
  },

  sssServiceInstallation: {
    supabaseTable: "sss_service_installation",
    sourceSheet: "Service-Installation",
    primaryKey: "id",
    description:
      "Service Installation stage, owned by src/pages/ServiceInstallation.jsx (route /serviceinstallation), " +
      "migration 0052. Replaces this page's old Apps Script/Google Sheets + Drive backend (VITE_APPS_SCRIPT_API, " +
      "VITE_GOOGLE_SHEET_ID, VITE_SERVICE_INSTALLATION_FOLDER_ID, VITE_DRIVE_FOLDER_ID — all removed from .env). " +
      "UNLIKE every other stage table above, this one is NOT keyed off tickets.uuid — it's a standalone log fed " +
      "by two independent writers: (1) a separate external 'OTP system' (not part of this codebase) INSERTs a " +
      "row per installation job with the first 14 columns below plus `planned`; (2) this page UPDATEs that same " +
      "row once an engineer completes/defers the follow-up. Pending vs History: planned is not null and actual " +
      "is null -> Pending; both not null -> History. `actual` is only stamped when installation_follow_up is " +
      "submitted as 'Yes' (job genuinely completed) — 'No' and 'Next Date for Follow-Up' update the row in " +
      "place but leave it in Pending. This page's 'New Enquiry' modal (a trimmed copy of Ticket-and-Enquiry.jsx's " +
      "form) is unrelated to this table — it inserts a brand new root ticket into public.tickets directly.",
    fields: [
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "created_at", type: "timestamptz", note: "'Timestamp'. Written by the external OTP system." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "order_no", type: "text", note: "Written by the OTP system." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "is_installation_required", type: "text", note: "'Yes'/'No'. Written by the OTP system." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "company_name / contact_person_name / contact_person_no", type: "text", note: "Written by the OTP system." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "item_name / qty / serial / si_no", type: "text/numeric", note: "Written by the OTP system." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "invoice_date / invoice_no / invoice_copy_upload / actual_material_rcvd", type: "date/text", note: "Written by the OTP system." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "planned", type: "timestamptz", note: "Readiness stamp — written by the OTP system, gates the Pending tab." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "actual", type: "timestamptz", note: "Written by this page, only when installation_follow_up = 'Yes'." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "installation_follow_up", type: "text", note: "'Yes' | 'No' | 'Next Date for Follow-Up'. Written by this page's Approval dialog." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "service_type / engineer_name", type: "text", note: "Written by this page, only when installation_follow_up = 'Yes'." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "service_report_file", type: "text", note: "File URL in the 'ticket_enquiry' Storage bucket (path prefix 'service_installation/'). NOT in the original column list the user specified — added by explicit follow-up decision (2026-09-02) to keep the old Apps Script version's file-upload feature." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "next_date / what_did_customer_say", type: "date/text", note: "Written by this page for all three installation_follow_up outcomes." },
      { sheetColumn: null, sheetIndex: null, sheetField: null, supabaseColumn: "delay", type: "integer", note: "Trigger-computed: greatest(0, round((actual - planned) in minutes)). Never written by the frontend." },
    ],
  },
};
